pao:
  script:
    #- apt-get update
    #- apt-get install -y python-dev python-pip
    - conda env list
    - test/bin/python setup.py develop
    - test/bin/pip install nose
    - test/bin/pip install coverage
    - test/bin/coverage run nosetests --with-xunit --with-coverage --cover-xml .
    - test/bin/coverage report -m
