name: pyomo-checks

on:
  push:
    branches:
      - master

jobs:
  pyomo-checks:
    name: ${{ matrix.install }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        install: ["conda", "github-main", "pypi"]
        python-version: [3.9]
    timeout-minutes: 90

    steps:
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda init bash
        conda env list

    - uses: actions/checkout@v1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda env list
        conda activate test
        conda config --set always_yes yes
        python -m pip install --upgrade pip
        pip install wheel
        pip install nose pyyaml numpy scipy
        conda install -c conda-forge coincbc glpk ipopt
        case "${{matrix.install}}" in
        'conda')
            pip install --quiet git+https://github.com/PyUtilib/pyutilib
            pip install --quiet git+https://github.com/Pyomo/pyomo
            ;;
        'github-main')
            pip install --quiet git+https://github.com/PyUtilib/pyutilib
            pip install --quiet git+https://github.com/Pyomo/pyomo
            ;;
        'pypi')
            pip install --quiet pyutilib
            pip install --quiet pyomo
            ;;
        esac
        python setup.py develop
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        nosetests -v .
